site_name: springboot



# pip install mkdocs-material
theme:
  language: 'en'
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'white'


extra_css:
  - 'css/app.css'



nav:
  - 公众号:
    - 既生synchronized，何生volatile？: hollis/02.md
    - 再有人问你Java内存模型是什么，就把这篇文章发给他: hollis/01.md
    - JVM内存结构 VS Java内存模型 VS Java对象模型: hollis/03.md
    - 再有人问你synchronized是什么，就把这篇文章发给他: hollis/04.md
    - 再有人问你volatile是什么，把这篇文章也发给他: hollis/05.md
    - Java的并发编程中的多线程问题到底是怎么回事儿？: hollis/06.md


# pip install pygments
# pip install pymdown-extensions
markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.critic
  - tables
  - pymdownx.mark


